name: sync-to-dev
on:
  push:
    branches:
      - main
      - 'hotfix-*'
      - 'release-*'
  pull_request:
    types: [closed]
jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Dump GitHub context
         env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
         run: echo "$GITHUB_CONTEXT"
       - name: Rebase through push
         env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions

          echo hello world
          
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          
          git checkout $BRANCH_NAME
          git rebase dev
          git add .
          git commit -m 'feature rebased'
          git push
          
          git checkout dev 
          git rebase $BRANCH_NAME
          git add .
          git commit -m "dev rebased"
          git push
          
          
    
      
